# Generated by Django 4.0.5 on 2023-05-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='audio',
            table='Audio',
        ),
    ]
